[0m12:21:13.409666 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdbe96b3150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdbe965da90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdbe96aa910>]}


============================== 12:21:13.413873 | ba6baeaa-1522-44cc-8ff1-fdf6ae5e84ef ==============================
[0m12:21:13.413873 [info ] [MainThread]: Running with dbt=1.9.0
[0m12:21:13.414762 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/ruicarvalho/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt_zoomcamp', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:21:13.432453 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/home/ruicarvalho/.dbt')}
[0m12:21:13.433159 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:21:13.471630 [debug] [MainThread]: Starter project path: /home/ruicarvalho/mynewenv/lib/python3.11/site-packages/dbt/include/starter_project
[0m12:21:13.507494 [info ] [MainThread]: 
Your new dbt project "dbt_zoomcamp" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:21:13.508297 [info ] [MainThread]: Setting up your profile.
[0m12:21:53.551927 [info ] [MainThread]: Profile dbt_zoomcamp written to /home/ruicarvalho/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:21:53.553665 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 40.210842, "process_in_blocks": "832", "process_kernel_time": 0.295441, "process_mem_max_rss": "93732", "process_out_blocks": "80", "process_user_time": 1.604651}
[0m12:21:53.554338 [debug] [MainThread]: Command `dbt init` succeeded at 12:21:53.554159 after 40.21 seconds
[0m12:21:53.554976 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdbe965da90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdbe9b5ba10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdbed039410>]}
[0m12:21:53.555647 [debug] [MainThread]: Flushing usage events
[0m12:21:53.896205 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:30:26.308917 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f096088d090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f096088db50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0960e45590>]}


============================== 12:30:26.313089 | 74f92903-e217-401c-9833-fce6e34c8533 ==============================
[0m12:30:26.313089 [info ] [MainThread]: Running with dbt=1.9.0
[0m12:30:26.314346 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/ruicarvalho/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m12:30:33.457893 [debug] [MainThread]: Starter project path: /home/ruicarvalho/mynewenv/lib/python3.11/site-packages/dbt/include/starter_project
[0m12:30:33.460996 [info ] [MainThread]: 
Your new dbt project "de_zoomcamp_final_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:30:33.461835 [info ] [MainThread]: Setting up your profile.
[0m12:31:03.657498 [info ] [MainThread]: Profile de_zoomcamp_final_project written to /home/ruicarvalho/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:31:03.659120 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 37.418827, "process_in_blocks": "72", "process_kernel_time": 0.242557, "process_mem_max_rss": "93692", "process_out_blocks": "96", "process_user_time": 1.633809}
[0m12:31:03.659947 [debug] [MainThread]: Command `dbt init` succeeded at 12:31:03.659751 after 37.42 seconds
[0m12:31:03.660503 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0960a57790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f09608a7090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0964341450>]}
[0m12:31:03.661250 [debug] [MainThread]: Flushing usage events
[0m12:31:04.025206 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:03:36.228335 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd72f64a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd72f64a3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd72f67dcd0>]}


============================== 17:03:36.248524 | 49b0e2c4-b9c9-4821-aa8a-259fe78d4fb9 ==============================
[0m17:03:36.248524 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:03:36.249660 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/ruicarvalho/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:03:36.250429 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ruicarvalho/de_zoomcamp_final_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:03:36.253184 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.1189278, "process_in_blocks": "120", "process_kernel_time": 0.290917, "process_mem_max_rss": "89584", "process_out_blocks": "8", "process_user_time": 1.622307}
[0m17:03:36.253891 [debug] [MainThread]: Command `dbt run` failed at 17:03:36.253679 after 0.12 seconds
[0m17:03:36.255360 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd72f67dc90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd72f4bb810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd72f4a1650>]}
[0m17:03:36.256373 [debug] [MainThread]: Flushing usage events
[0m17:03:36.600220 [debug] [MainThread]: An error was encountered while trying to flush usage events
